export const FETCH_SCREENS = 'FETCH_SCREENS'
export const DELETE_SCREEN_INIT = 'DELETE_SCREEN_INIT'
export const DELETE_SCREEN = 'DELETE_SCREEN'

export const CREATE_SCREEN_INIT = 'CREATE_SCREEN_INIT'
export const CREATE_SCREEN = 'CREATE_SCREEN'

export const UPDATE_SCREEN_INIT = 'UPDATE_SCREEN_INIT'
export const UPDATE_SCREEN = 'UPDATE_SCREEN'


export const FETCH_USERS = 'FETCH_USERS'

export const CREATE_USER_INIT = 'CREATE_USER_INIT'
export const CREATE_USER = 'CREATE_USER'

export const DELETE_USER_INIT = 'DELETE_USER_INIT'
export const DELETE_USER = 'DELETE_USER'

export const UPDATE_USER_INIT = 'UPDATE_USER_INIT'
export const UPDATE_USER = 'UPDATE_USER'


export const FETCH_ROLES  ='FETCH_ROLES'

export const CREATE_ROLE_INIT = 'CREATE_ROLE_INIT'
export const CREATE_ROLE = 'CREATE_ROLE'